/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import classe.Dados;

public class Menu extends javax.swing.JFrame {

  private Dados clsdados;
  public void setdados (Dados clsdados){
      this.clsdados =clsdados;
  }
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        Deskpanel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnarquivos = new javax.swing.JMenu();
        mnarquivosclientes = new javax.swing.JMenuItem();
        mnarquivosprodutos = new javax.swing.JMenuItem();
        mnarquivosusuarios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnarquivosAlterarSenha = new javax.swing.JMenuItem();
        mnarquivosAlterarUsuario = new javax.swing.JMenuItem();
        mnarquivosSair = new javax.swing.JMenuItem();
        mnmovimentos = new javax.swing.JMenu();
        mnmovimentosVendas = new javax.swing.JMenuItem();
        mnmovimentosRelVendas = new javax.swing.JMenuItem();
        mnajuda = new javax.swing.JMenu();
        mnajudaSobre = new javax.swing.JMenuItem();
        mnajudaAjuda = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema ");

        Deskpanel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout DeskpanelLayout = new javax.swing.GroupLayout(Deskpanel);
        Deskpanel.setLayout(DeskpanelLayout);
        DeskpanelLayout.setHorizontalGroup(
            DeskpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        DeskpanelLayout.setVerticalGroup(
            DeskpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        mnarquivos.setText("Arquivos");

        mnarquivosclientes.setText("Cliente");
        mnarquivos.add(mnarquivosclientes);

        mnarquivosprodutos.setText("Produtos");
        mnarquivos.add(mnarquivosprodutos);

        mnarquivosusuarios.setText("Usuarios");
        mnarquivosusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnarquivosusuariosActionPerformed(evt);
            }
        });
        mnarquivos.add(mnarquivosusuarios);
        mnarquivos.add(jSeparator1);

        mnarquivosAlterarSenha.setText("Alterar Senha");
        mnarquivos.add(mnarquivosAlterarSenha);

        mnarquivosAlterarUsuario.setText("Alterar Usuario");
        mnarquivos.add(mnarquivosAlterarUsuario);

        mnarquivosSair.setText("Sair");
        mnarquivos.add(mnarquivosSair);

        jMenuBar1.add(mnarquivos);

        mnmovimentos.setText("Movimentos");

        mnmovimentosVendas.setText("Vendas");
        mnmovimentos.add(mnmovimentosVendas);

        mnmovimentosRelVendas.setText("relatorios de Vendas");
        mnmovimentos.add(mnmovimentosRelVendas);

        jMenuBar1.add(mnmovimentos);

        mnajuda.setText("Ajuda");

        mnajudaSobre.setText("Sobre");
        mnajuda.add(mnajudaSobre);

        mnajudaAjuda.setText("Ajuda");
        mnajuda.add(mnajudaAjuda);

        jMenuBar1.add(mnajuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Deskpanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Deskpanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnarquivosusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnarquivosusuariosActionPerformed
        frmUsuario usuario = new frmUsuario();
        usuario.setdados(clsdados);
        Deskpanel.add(usuario);
        usuario.show();
    }//GEN-LAST:event_mnarquivosusuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Deskpanel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu mnajuda;
    private javax.swing.JMenuItem mnajudaAjuda;
    private javax.swing.JMenuItem mnajudaSobre;
    private javax.swing.JMenu mnarquivos;
    private javax.swing.JMenuItem mnarquivosAlterarSenha;
    private javax.swing.JMenuItem mnarquivosAlterarUsuario;
    private javax.swing.JMenuItem mnarquivosSair;
    private javax.swing.JMenuItem mnarquivosclientes;
    private javax.swing.JMenuItem mnarquivosprodutos;
    private javax.swing.JMenuItem mnarquivosusuarios;
    private javax.swing.JMenu mnmovimentos;
    private javax.swing.JMenuItem mnmovimentosRelVendas;
    private javax.swing.JMenuItem mnmovimentosVendas;
    // End of variables declaration//GEN-END:variables
}
